spring:
  application:
    name: bilim-app
  datasource:
    url: jdbc:postgresql://localhost:5432/bilimdb
    username: bilimuser
    password: bilimpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot-token: ${BOT_TOKEN:change_me}

jwt:
  secret: change_me
  expiration: 3600
server:
  port: 8090

springdoc:
  swagger-ui:
    path: /api/mobile/swagger-ui/index.html
    config-url: /api/mobile/v3/api-docs/swagger-config
  api-docs:
    path: /api/mobile/v3/api-docs

app:
  version: ${revision}