spring:
  application:
    name: bilim-web
  datasource:
    url: jdbc:postgresql://localhost:5432/bilimdb
    username: bilimuser
    password: bilimpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  secret-key: ChangeMe1234567890
server:
  port: 8091

app:
  version: 0.0.1
